version: '3.1'
services:

  mongo:
    image: mongo:4.2
    environment:
      - MONGO_DATA_DIR=/data
    volumes:
      - ./.cache/mongo:/data
    ports:
      - 27017:27017
    command: mongod

  postgres:
    build:
      context: ./postgres
    command: postgres -c 'max_connections=300'
    environment:
      POSTGRES_DB: optimacros
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: pass1
    volumes:
      - ./.cache/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  server:
    build:
      context: ./server
    env_file: ./development.env
    volumes:
#      - ./server/dist:/var/www/server/dist
      - ./server/src:/var/www/server/src
    ports:
      - "9080:9080"
      - "8080:8080"
